apiVersion: v1
kind: Pod
metadata:
  name: internal-create
spec:
  serviceAccountName: internal-create
  restartPolicy: OnFailure
  containers:
    - image: ghcr.io/lasyard/coding-go/k8s/internal-create:v1
      imagePullPolicy: IfNotPresent
      name: internal-create
      resources:
        requests:
          cpu: "1"
          memory: 100Mi
        limits:
          cpu: "1"
          memory: 100Mi
