apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-svc
  template:
    metadata:
      labels:
        app: upload-svc
    spec:
      containers:
        - name: upload-svc
          image: ghcr.io/lasyard/coding-go/k8s/upload-svc:v1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: upload-volume
              mountPath: /var/uploads
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
            requests:
              memory: "64Mi"
              cpu: "250m"
      volumes:
        - name: upload-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: upload-svc
spec:
  selector:
    app: upload-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: upload-svc-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /upload
            pathType: Prefix
            backend:
              service:
                name: upload-svc
                port:
                  number: 80
